if (keyboard_check_pressed(ord("F"))||keyboard_check_pressed(vk_f11)){
	window_set_fullscreen(!window_get_fullscreen())
}
if (global.screentype = "start"){
	if (mouse_check_button_pressed(mb_left)){
		room_goto(MENU_main)	
	}
}
if (room = NIGHT_1){
	global.time += 1
}
if (global.time > 21720 && global.screentype = "ingame"){
	audio_stop_all()
	show_message("YOU WON!")
	room_goto(START)
	global.screentype = "start"
	global.camflipped = false
	global.nightcompletion = 0
	global.currentnight = 0
}
if (global.screentype = "customnight"){
	scr_customgimpsncheats()
	if (keyboard_check_pressed(vk_right)){
		audio_play_sound(sfx_customnight_up, 1, false)
		audio_play_sound(sfx_customnight_down, 1, false)
		if (customnightchallenge = "None"){
			customnightchallenge = "Warmth"
			np_setpresence("Challenge: " + customnightchallenge,"Custom Night", "bigicon", "")
			AI_mathi = 8
			AI_manimo = 12
			AI_sports = 0
			AI_pravi = 10
			AI_ava = 0
			AI_joetube = 0
			AI_marze = 0
			AI_dan = 11
			AI_beanie = 12
			GIMP_nut = true
			GIMP_mathis = false
			GIMP_faulty = false
			GIMP_party = false
			GIMP_adrenaline = true
			GIMP_lightsleep = false
			GIMP_hungry = true
			GIMP_hotsoup = false
			CHEAT_kinddan = true
			CHEAT_arthritis = false
			CHEAT_heavysleep = false
			CHEAT_eyes = false
			CHEAT_pokeblocks = false
		}else if (customnightchallenge = "Warmth"){
			customnightchallenge = "Biting Cold"
			np_setpresence("Challenge: " + customnightchallenge,"Custom Night", "bigicon", "")
			AI_mathi = 0
			AI_manimo = 0
			AI_sports = 15
			AI_pravi = 0
			AI_ava = 15
			AI_joetube = 12
			AI_marze = 14
			AI_dan = 0
			AI_beanie = 0
			GIMP_nut = false
			GIMP_mathis = false
			GIMP_faulty = false
			GIMP_party = false
			GIMP_adrenaline = false
			GIMP_lightsleep = true
			GIMP_hungry = false
			GIMP_hotsoup = true
			CHEAT_kinddan = false
			CHEAT_arthritis = true
			CHEAT_heavysleep = false
			CHEAT_eyes = false
			CHEAT_pokeblocks = false
		}else if (customnightchallenge = "Biting Cold"){
			customnightchallenge = "Tryhards"
			np_setpresence("Challenge: " + customnightchallenge,"Custom Night", "bigicon", "")
			AI_mathi = 10
			AI_manimo = 10
			AI_sports = 10
			AI_pravi = 0
			AI_ava = 0
			AI_joetube = 10
			AI_marze = 10
			AI_dan = 10
			AI_beanie = 0
			GIMP_nut = false
			GIMP_mathis = false
			GIMP_faulty = true
			GIMP_party = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = false
			CHEAT_kinddan = true
			CHEAT_arthritis = false
			CHEAT_heavysleep = false
			CHEAT_eyes = false
			CHEAT_pokeblocks = false
		}else if (customnightchallenge = "Tryhards"){
			customnightchallenge = "Asylum Escapees"
			np_setpresence("Challenge: " + customnightchallenge,"Custom Night", "bigicon", "")
			AI_mathi = 14
			AI_manimo = 12
			AI_sports = 14
			AI_pravi = 8
			AI_ava = 0
			AI_joetube = 15
			AI_marze = 0
			AI_dan = 16
			AI_beanie = 0
			GIMP_nut = false
			GIMP_mathis = false
			GIMP_faulty = false
			GIMP_party = true
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = false
			CHEAT_kinddan = false
			CHEAT_arthritis = false
			CHEAT_heavysleep = false
			CHEAT_eyes = false
			CHEAT_pokeblocks = false
		}else if (customnightchallenge = "Asylum Escapees"){
			customnightchallenge = "The Circus"
			np_setpresence("Challenge: " + customnightchallenge,"Custom Night", "bigicon", "")
			AI_mathi = 0
			AI_manimo = 18
			AI_sports = 18
			AI_pravi = 10
			AI_ava = 0
			AI_joetube = 10
			AI_marze = 0
			AI_dan = 0
			AI_beanie = 7
			GIMP_nut = true
			GIMP_mathis = false
			GIMP_faulty = false
			GIMP_party = true
			GIMP_adrenaline = false
			GIMP_lightsleep = true
			GIMP_hungry = false
			GIMP_hotsoup = false
			CHEAT_kinddan = false
			CHEAT_arthritis = false
			CHEAT_heavysleep = false
			CHEAT_eyes = false
			CHEAT_pokeblocks = false
		}else if (customnightchallenge = "The Circus"){
			customnightchallenge = "Warriordan's Trial"
			np_setpresence("Challenge: " + customnightchallenge,"Custom Night", "bigicon", "")
			AI_mathi = 17
			AI_manimo = 12
			AI_sports = 0
			AI_pravi = 15
			AI_ava = 0
			AI_joetube = 15
			AI_marze = 0
			AI_dan = 17
			AI_beanie = 0
			GIMP_nut = false
			GIMP_mathis = false
			GIMP_faulty = true
			GIMP_party = false
			GIMP_adrenaline = true
			GIMP_lightsleep = false
			GIMP_hungry = true
			GIMP_hotsoup = false
			CHEAT_kinddan = false
			CHEAT_arthritis = false
			CHEAT_heavysleep = false
			CHEAT_eyes = false
			CHEAT_pokeblocks = false
		}else if (customnightchallenge = "Warriordan's Trial"){
			customnightchallenge = "Lullaby"
			np_setpresence("Challenge: " + customnightchallenge,"Custom Night", "bigicon", "")
			AI_mathi = 13
			AI_manimo = 0
			AI_sports = 0
			AI_pravi = 15
			AI_ava = 20
			AI_joetube = 15
			AI_marze = 12
			AI_dan = 0
			AI_beanie = 15
			GIMP_nut = false
			GIMP_mathis = false
			GIMP_faulty = true
			GIMP_party = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = false
			CHEAT_kinddan = false
			CHEAT_arthritis = false
			CHEAT_heavysleep = true
			CHEAT_eyes = false
			CHEAT_pokeblocks = false
		}else if (customnightchallenge = "Lullaby"){
			customnightchallenge = "Bean boppers"
			np_setpresence("Challenge: " + customnightchallenge,"Custom Night", "bigicon", "")
			AI_mathi = 10
			AI_manimo = 0
			AI_sports = 8
			AI_pravi = 10
			AI_ava = 16
			AI_joetube = 0
			AI_marze = 7
			AI_dan = 0
			AI_beanie = 18
			GIMP_nut = true
			GIMP_mathis = false
			GIMP_faulty = false
			GIMP_party = false
			GIMP_adrenaline = false
			GIMP_lightsleep = true
			GIMP_hungry = true
			GIMP_hotsoup = false
			CHEAT_kinddan = false
			CHEAT_arthritis = false
			CHEAT_heavysleep = false
			CHEAT_eyes = false
			CHEAT_pokeblocks = false
		}else if (customnightchallenge = "Bean boppers"){
			customnightchallenge = "Crack shot"
			np_setpresence("Challenge: " + customnightchallenge,"Custom Night", "bigicon", "")
			AI_mathi = 13
			AI_manimo = 9
			AI_sports = 13
			AI_pravi = 9
			AI_ava = 13
			AI_joetube = 9
			AI_marze = 13
			AI_dan = 9
			AI_beanie = 13
			GIMP_nut = false
			GIMP_mathis = false
			GIMP_faulty = true
			GIMP_party = false
			GIMP_adrenaline = false
			GIMP_lightsleep = true
			GIMP_hungry = false
			GIMP_hotsoup = false
			CHEAT_kinddan = false
			CHEAT_arthritis = false
			CHEAT_heavysleep = false
			CHEAT_eyes = false
			CHEAT_pokeblocks = true
		}else if (customnightchallenge = "Crack shot"){
			customnightchallenge = "BUG_REPORT"
			np_setpresence("Challenge: " + customnightchallenge,"Custom Night", "bigicon", "")
			AI_mathi = 1
			AI_manimo = 2
			AI_sports = 3
			AI_pravi = 4
			AI_ava = 5
			AI_joetube = 13
			AI_marze = 6
			AI_dan = 7
			AI_beanie = 8
			GIMP_nut = false
			GIMP_mathis = false
			GIMP_faulty = true
			GIMP_party = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = false
			CHEAT_kinddan = false
			CHEAT_arthritis = false
			CHEAT_heavysleep = false
			CHEAT_eyes = false
			CHEAT_pokeblocks = false
		}else if (customnightchallenge = "BUG_REPORT"){
			customnightchallenge = "Deutsche Prazision"
			np_setpresence("Challenge: " + customnightchallenge,"Custom Night", "bigicon", "")
			AI_mathi = 20
			AI_manimo = 0
			AI_sports = 0
			AI_pravi = 20
			AI_ava = 0
			AI_joetube = 20
			AI_marze = 0
			AI_dan = 0
			AI_beanie = 0
			GIMP_nut = false
			GIMP_mathis = false
			GIMP_faulty = true
			GIMP_party = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = true
			GIMP_hotsoup = false
			CHEAT_kinddan = false
			CHEAT_arthritis = false
			CHEAT_heavysleep = false
			CHEAT_eyes = false
			CHEAT_pokeblocks = false
		}else if (customnightchallenge = "Deutsche Prazision"){
			customnightchallenge = "Late night run"
			np_setpresence("Challenge: " + customnightchallenge,"Custom Night", "bigicon", "")
			AI_mathi = 0
			AI_manimo = 17
			AI_sports = 17
			AI_pravi = 0
			AI_ava = 17
			AI_joetube = 0
			AI_marze = 15
			AI_dan = 16
			AI_beanie = 12
			GIMP_nut = false
			GIMP_mathis = false
			GIMP_faulty = true
			GIMP_party = false
			GIMP_adrenaline = true
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = true
			CHEAT_kinddan = false
			CHEAT_arthritis = false
			CHEAT_heavysleep = false
			CHEAT_eyes = true
			CHEAT_pokeblocks = false
		}else if (customnightchallenge = "Late night run"){
			customnightchallenge = "Mongolia Mode"
			np_setpresence("Challenge: " + customnightchallenge,"Custom Night", "bigicon", "")
			AI_mathi = 20
			AI_manimo = 20
			AI_sports = 20
			AI_pravi = 20
			AI_ava = 20
			AI_joetube = 20
			AI_marze = 20
			AI_dan = 20
			AI_beanie = 20
			GIMP_nut = false
			GIMP_mathis = false
			GIMP_faulty = false
			GIMP_party = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = false
			CHEAT_kinddan = false
			CHEAT_arthritis = false
			CHEAT_heavysleep = false
			CHEAT_eyes = false
			CHEAT_pokeblocks = false
		}else if (customnightchallenge = "Mongolia Mode"){
			customnightchallenge = "Jesse's Challenge"
			np_setpresence("Challenge: " + customnightchallenge,"Custom Night", "bigicon", "")
			AI_mathi = 20
			AI_manimo = 20
			AI_sports = 20
			AI_pravi = 20
			AI_ava = 20
			AI_joetube = 20
			AI_marze = 20
			AI_dan = 20
			AI_beanie = 20
			GIMP_nut = true
			GIMP_mathis = false
			GIMP_faulty = true
			GIMP_party = true
			GIMP_adrenaline = true
			GIMP_lightsleep = true
			GIMP_hungry = true
			GIMP_hotsoup = true
			CHEAT_kinddan = false
			CHEAT_arthritis = false
			CHEAT_heavysleep = false
			CHEAT_eyes = false
			CHEAT_pokeblocks = false
		}else if (customnightchallenge = "Jesse's Challenge"){
			customnightchallenge = "None"
			np_setpresence("Challenge: " + customnightchallenge,"Custom Night", "bigicon", "")
			AI_mathi = 0
			AI_manimo = 0
			AI_sports = 0
			AI_pravi = 0
			AI_ava = 0
			AI_joetube = 0
			AI_marze = 0
			AI_dan = 0
			AI_beanie = 0
			GIMP_nut = false
			GIMP_mathis = false
			GIMP_faulty = false
			GIMP_party = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = false
			CHEAT_kinddan = false
			CHEAT_arthritis = false
			CHEAT_heavysleep = false
			CHEAT_eyes = false
			CHEAT_pokeblocks = false
		}
	}
}
inputdelay -= 1