// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function scr_customchallenge(){
	switch (customnightchallenge){
		case "None":
			AI_mathi = 0
			AI_manimo = 0
			AI_sports = 0
			AI_pravi = 0
			AI_ava = 0
			AI_joetube = 0
			AI_marze = 0
			AI_dan = 0
			AI_beanie = 0
			AI_coconut = 0
			AI_dj = 0
			AI_valerix = 0
			AI_roachy = 0
			GIMP_nut = false
			GIMP_faulty = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = false
			GIMP_antivaxx = false
			GIMP_powerhungry = false
			GIMP_blackout = false
		break;
		case "Warmth":
			AI_mathi = 15
			AI_manimo = 17
			AI_sports = 0
			AI_pravi = 14
			AI_ava = 0
			AI_joetube = 0
			AI_marze = 0
			AI_dan = 15
			AI_beanie = 10
			AI_coconut = 14
			AI_dj = 0
			AI_valerix = 15
			AI_roachy = 0
			GIMP_nut = false
			GIMP_faulty = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = false
			GIMP_antivaxx = false
			GIMP_powerhungry = false
			GIMP_blackout = false
		break;
		case "Biting Cold":
			AI_mathi = 0
			AI_manimo = 0
			AI_sports = 18
			AI_pravi = 0
			AI_ava = 6
			AI_joetube = 14
			AI_marze = 11
			AI_dan = 0
			AI_beanie = 0
			AI_coconut = 0
			AI_dj = 11
			AI_valerix = 0
			AI_roachy = 16
			GIMP_nut = false
			GIMP_faulty = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = false
			GIMP_antivaxx = false
			GIMP_powerhungry = false
			GIMP_blackout = false
		break;
		case "Lullaby":
			AI_mathi = 12
			AI_manimo = 0
			AI_sports = 0
			AI_pravi = 10
			AI_ava = 10
			AI_joetube = 15
			AI_marze = 0
			AI_dan = 0
			AI_beanie = 14
			AI_coconut = 0
			AI_dj = 0
			AI_valerix = 0
			AI_roachy = 7
			GIMP_nut = false
			GIMP_faulty = false
			GIMP_adrenaline = false
			GIMP_lightsleep = true
			GIMP_hungry = false
			GIMP_hotsoup = false
			GIMP_antivaxx = false
			GIMP_powerhungry = false
			GIMP_blackout = false
		break;
		case "Bean Boppers":
			AI_mathi = 14
			AI_manimo = 0
			AI_sports = 12
			AI_pravi = 14
			AI_ava = 11
			AI_joetube = 11
			AI_marze = 8
			AI_dan = 13
			AI_beanie = 20
			AI_coconut = 11
			AI_dj = 5
			AI_valerix = 5
			AI_roachy = 3
			GIMP_nut = false
			GIMP_faulty = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = false
			GIMP_antivaxx = false
			GIMP_powerhungry = false
			GIMP_blackout = false
		break;
		case "Nuisances":
			AI_mathi = 0
			AI_manimo = 0
			AI_sports = 0
			AI_pravi = 14
			AI_ava = 8
			AI_joetube = 16
			AI_marze = 0
			AI_dan = 0
			AI_beanie = 0
			AI_coconut = 13
			AI_dj = 14
			AI_valerix = 0
			AI_roachy = 0
			GIMP_nut = true
			GIMP_faulty = false
			GIMP_adrenaline = false
			GIMP_lightsleep =true
			GIMP_hungry = true
			GIMP_hotsoup = false
			GIMP_antivaxx = true
			GIMP_powerhungry = true
			GIMP_blackout = false
		break;
		case "Running in the Dark":
			AI_mathi = 0
			AI_manimo = 14
			AI_sports = 14
			AI_pravi = 0
			AI_ava = 0
			AI_joetube = 16
			AI_marze = 13
			AI_dan = 0
			AI_beanie = 0
			AI_coconut = 0
			AI_dj = 0
			AI_valerix = 12
			AI_roachy = 0
			GIMP_nut = false
			GIMP_faulty = false
			GIMP_adrenaline = true
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = true
			GIMP_antivaxx = false
			GIMP_powerhungry = false
			GIMP_blackout = true
		break;
		case "Power's cut":
			AI_mathi = 0
			AI_manimo = 0
			AI_sports = 13
			AI_pravi = 15
			AI_ava = 0
			AI_joetube = 0
			AI_marze = 0
			AI_dan = 12
			AI_beanie = 12
			AI_coconut = 0
			AI_dj = 15
			AI_valerix = 0
			AI_roachy = 13
			GIMP_nut = false
			GIMP_faulty = true
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = true
			GIMP_hotsoup = false
			GIMP_antivaxx = false
			GIMP_powerhungry = false
			GIMP_blackout = true
		break;
		case "Tryhards":
			AI_mathi = 12
			AI_manimo = 12
			AI_sports = 12
			AI_pravi = 0
			AI_ava = 0
			AI_joetube = 12
			AI_marze = 12
			AI_dan = 12
			AI_beanie = 0
			AI_coconut = 12
			AI_dj = 0
			AI_valerix = 0
			AI_roachy = 0
			GIMP_nut = false
			GIMP_faulty = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = true
			GIMP_antivaxx = false
			GIMP_powerhungry = false
			GIMP_blackout = false
		break;
		case "9-13":
			AI_mathi = 9
			AI_manimo = 9
			AI_sports = 9
			AI_pravi = 13
			AI_ava = 13
			AI_joetube = 9
			AI_marze = 9
			AI_dan = 13
			AI_beanie = 9
			AI_coconut = 13
			AI_dj = 13
			AI_valerix = 9
			AI_roachy = 13
			GIMP_nut = false
			GIMP_faulty = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = false
			GIMP_antivaxx = false
			GIMP_powerhungry = false
			GIMP_blackout = false
		break;
		case "Duetsche Prazision":
			AI_mathi = 20
			AI_manimo = 0
			AI_sports = 0
			AI_pravi = 20
			AI_ava = 0
			AI_joetube = 20
			AI_marze = 0
			AI_dan = 0
			AI_beanie = 0
			AI_coconut = 0
			AI_dj = 20
			AI_valerix = 0
			AI_roachy = 0
			GIMP_nut = false
			GIMP_faulty = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = false
			GIMP_antivaxx = true
			GIMP_powerhungry = true
			GIMP_blackout = false
		break;
		case "Ew, it's the Europeans":
			AI_mathi = 13
			AI_manimo = 14
			AI_sports = 14
			AI_pravi = 12
			AI_ava = 0
			AI_joetube = 15
			AI_marze = 0
			AI_dan = 0
			AI_beanie = 0
			AI_coconut = 0
			AI_dj = 13
			AI_valerix = 16
			AI_roachy = 12
			GIMP_nut = false
			GIMP_faulty = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = false
			GIMP_antivaxx = false
			GIMP_powerhungry = false
			GIMP_blackout = false
		break;
		case "Warriordan's Trial":
			AI_mathi = 15
			AI_manimo = 14
			AI_sports = 14
			AI_pravi = 17
			AI_ava = 0
			AI_joetube = 0
			AI_marze = 0
			AI_dan = 20
			AI_beanie = 0
			AI_coconut = 0
			AI_dj = 0
			AI_valerix = 12
			AI_roachy = 14
			GIMP_nut = false
			GIMP_faulty = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = false
			GIMP_antivaxx = false
			GIMP_powerhungry = false
			GIMP_blackout = false
		break;
		case "Crackshot":
			AI_mathi = 15
			AI_manimo = 15
			AI_sports = 15
			AI_pravi = 15
			AI_ava = 15
			AI_joetube = 15
			AI_marze = 15
			AI_dan = 15
			AI_beanie = 15
			AI_coconut = 0
			AI_dj = 0
			AI_valerix = 0
			AI_roachy = 0
			GIMP_nut = false
			GIMP_faulty = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = false
			GIMP_antivaxx = false
			GIMP_powerhungry = false
			GIMP_blackout = false
		break;
		case "Mongolia Mode":
			AI_mathi = 20
			AI_manimo = 20
			AI_sports = 20
			AI_pravi = 20
			AI_ava = 20
			AI_joetube = 20
			AI_marze = 20
			AI_dan = 20
			AI_beanie = 20
			AI_coconut = 20
			AI_dj = 20
			AI_valerix = 20
			AI_roachy = 20
			GIMP_nut = false
			GIMP_faulty = false
			GIMP_adrenaline = false
			GIMP_lightsleep = false
			GIMP_hungry = false
			GIMP_hotsoup = false
			GIMP_antivaxx = false
			GIMP_powerhungry = false
			GIMP_blackout = false
		break;
		case "Jesse's Challenge":
			AI_mathi = 20
			AI_manimo = 20
			AI_sports = 20
			AI_pravi = 20
			AI_ava = 20
			AI_joetube = 20
			AI_marze = 20
			AI_dan = 20
			AI_beanie = 20
			AI_coconut = 20
			AI_dj = 20
			AI_valerix = 20
			AI_roachy = 20
			GIMP_nut = true
			GIMP_faulty = true
			GIMP_adrenaline = true
			GIMP_lightsleep = true
			GIMP_hungry = true
			GIMP_hotsoup = true
			GIMP_antivaxx = true
			GIMP_powerhungry = true
			GIMP_blackout = true
		break;
		default:
			
		break;
	}
}