draw_set_font(Normal)
draw_text(0, 20, "endless long - survive 30 minutes in endless mode (5 nights)")
draw_text(0, 40, "all deaths - die to everyone, non-jumpscarers must be active for their count 0/9")
draw_text(0, 60, "pravi hate - get rid of pravi within 5 seconds of him spawning")
draw_text(0, 80, "pravi love - let pravi stay active for 15 seconds")
draw_text(0, 100, "transphobia - use the flashlight on beanie 15 times in one night")
draw_text(0, 120, "jotube - with joetube at 10 or more, never let him leave his room")
draw_text(0, 140, "custom - beat all custom night challenges")
draw_text(0, 160, "bill cipher - cheat death")
draw_text(0, 180, "lunyaner - never let ava's box wind down below 50% with her at 15 or more")
draw_text(0, 200, "marze - with marze at 10 or more, never let her leave her room")
draw_text(0, 220, "week 1 perfect - beat week 1 on a new save without dying once")
draw_text(0, 240, "week 2 perfect - beat week 2 on a new save without dying once")
